# FastF1 Exploration

this will be a notebook to learn FastF1 before using it in my project. Used the 2026 Italian Grand Prix as the demo.

Goals of this will be:
- understand the FastF1 sessions and event metadata
- Inspect the available lap data
- Identify useful race strategy  and pace columns
- Explore driver, stint, tyre and race status information.

In [1]:
import fastf1

In [2]:
fastf1.__version__

'3.8.3'

In [3]:
import os
os.getcwd()

'/Users/mutaz/Code/f1-pit-wall-intelligence/notebooks'

In [4]:
fastf1.Cache.enable_cache("../cache")

In [5]:
session = fastf1.get_session(
    2026,
    "Italian Grand Prix",
    "R"
)

In [6]:
type(session)

fastf1.core.Session

In [7]:
session.name

'Race'

In [8]:
session.event

RoundNumber                                                   13
Country                                                    Italy
Location                                                   Monza
OfficialEventName    FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2026
EventDate                                    2026-09-06 00:00:00
EventName                                     Italian Grand Prix
EventFormat                                         conventional
Session1                                              Practice 1
Session1Date                           2026-09-04 12:30:00+02:00
Session1DateUtc                              2026-09-04 10:30:00
Session2                                              Practice 2
Session2Date                           2026-09-04 16:00:00+02:00
Session2DateUtc                              2026-09-04 14:00:00
Session3                                              Practice 3
Session3Date                           2026-09-05 12:30:00+02:00
Session3DateUtc                              2026-09-05 10:30:00
Session4                                              Qualifying
Session4Date                           2026-09-05 16:00:00+02:00
Session4DateUtc                              2026-09-05 14:00:00
Session5                                                    Race
Session5Date                           2026-09-06 15:00:00+02:00
Session5DateUtc                              2026-09-06 13:00:00
F1ApiSupport                                                True
Name: 14, dtype: object

In [9]:
session.load()

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 12 completed the race distance 00:00.013000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '3', '1', '81', '44', '10', '41', '43', '22', '5', '27', '55', '30', '87', '31', '23', '11', '77', '18', '14', '16']

In [10]:
laps = session.laps

In [11]:
type(laps)

fastf1.core.Laps

In [12]:
laps.shape

(1054, 31)

In [13]:
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:58:27.555000,NOR,1,0 days 00:01:31.580000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:31.558000,...,True,McLaren,0 days 00:56:55.761000,2026-09-06 13:03:30.937,1,7.0,False,,False,False
1,0 days 00:59:54.470000,NOR,1,0 days 00:01:26.915000,2.0,1.0,NaT,NaT,0 days 00:00:28.318000,0 days 00:00:30.159000,...,True,McLaren,0 days 00:58:27.555000,2026-09-06 13:05:02.731,1,6.0,False,,False,True
2,0 days 01:02:10.297000,NOR,1,0 days 00:02:15.827000,3.0,1.0,NaT,0 days 01:02:05.923000,0 days 00:00:36.828000,0 days 00:00:40.413000,...,True,McLaren,0 days 00:59:54.470000,2026-09-06 13:06:29.646,1245,6.0,False,,False,False
3,0 days 01:34:43.527000,NOR,1,NaT,4.0,2.0,0 days 01:32:46.490000,NaT,NaT,0 days 00:00:39.475000,...,True,McLaren,0 days 01:32:24.927000,2026-09-06 13:39:00.103,1,6.0,False,,False,False
4,0 days 01:38:01.292000,NOR,1,NaT,5.0,2.0,NaT,NaT,NaT,0 days 00:00:33.842000,...,True,McLaren,0 days 01:34:43.527000,2026-09-06 13:41:18.703,1,6.0,False,,False,False

In [14]:
""" 
Driver        → three-letter driver abbreviation
DriverNumber  → car number
LapTime       → total lap duration
LapNumber     → lap number for that driver
Stint         → which tyre stint they're on
PitOutTime    → when they exited pit lane
PitInTime     → when they entered pit lane
Sector1Time   → sector 1 duration
Sector2Time   → sector 2 duration
FreshTyre     → whether tyre set was fresh
Team          → constructor
Position      → driver's position
TrackStatus   → track/race-control state
Deleted       → whether lap was deleted
IsAccurate    → whether FastF1 considers timing reliable
"""

" \nDriver        → three-letter driver abbreviation\nDriverNumber  → car number\nLapTime       → total lap duration\nLapNumber     → lap number for that driver\nStint         → which tyre stint they're on\nPitOutTime    → when they exited pit lane\nPitInTime     → when they entered pit lane\nSector1Time   → sector 1 duration\nSector2Time   → sector 2 duration\nFreshTyre     → whether tyre set was fresh\nTeam          → constructor\nPosition      → driver's position\nTrackStatus   → track/race-control state\nDeleted       → whether lap was deleted\nIsAccurate    → whether FastF1 considers timing reliable\n"

In [15]:
laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [16]:
""" 
Identity / race context: tells us who/where in the race this row belongs to
  - Driver
  - DriverNumber
  - Team
  - LapNumber
  - Position
lap/sector timing: tells us how long things took
  - LapTime
  - Sector1Time
  - Sector2Time
  - Sector3Time
  - Time
  - LapStartTime
  - LapStartDate
  - Sector1SessionTime
  - Sector2SessionTime
  - Sector3SessionTime
pit/stint/tyre: strategy/tyre lifecycle
  - Stint
  - PitOutTime
  - PitInTime
  - Compound
  - TyreLife
  - FreshTyre 
speed traps: point-speed measurements
  - SpeedI1
  - SpeedI2
  - SpeedFL
  - SpeedST
Lap/status/quality information: whether the lap is valid/reliable and what track conditions applied
  - IsPersonalBest
  - TrackStatus
  - Deleted
  - DeletedReason
  - FastF1Generated
  - IsAccurate
"""

' \nIdentity / race context: tells us who/where in the race this row belongs to\n  - Driver\n  - DriverNumber\n  - Team\n  - LapNumber\n  - Position\nlap/sector timing: tells us how long things took\n  - LapTime\n  - Sector1Time\n  - Sector2Time\n  - Sector3Time\n  - Time\n  - LapStartTime\n  - LapStartDate\n  - Sector1SessionTime\n  - Sector2SessionTime\n  - Sector3SessionTime\npit/stint/tyre: strategy/tyre lifecycle\n  - Stint\n  - PitOutTime\n  - PitInTime\n  - Compound\n  - TyreLife\n  - FreshTyre \nspeed traps: point-speed measurements\n  - SpeedI1\n  - SpeedI2\n  - SpeedFL\n  - SpeedST\nLap/status/quality information: whether the lap is valid/reliable and what track conditions applied\n  - IsPersonalBest\n  - TrackStatus\n  - Deleted\n  - DeletedReason\n  - FastF1Generated\n  - IsAccurate\n'

In [17]:
""" 
small first analysis
"""
[
    "Driver",
    "LapNumber",
    "LapTime",
    "Stint",
    "Compound",
    "TyreLife",
    "FreshTyre",
    "PitInTime",
    "PitOutTime",
    "TrackStatus",
    "Position",
    "IsAccurate"
]

['Driver',
 'LapNumber',
 'LapTime',
 'Stint',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'PitInTime',
 'PitOutTime',
 'TrackStatus',
 'Position',
 'IsAccurate']

In [18]:
analysis_cols = [
    "Driver",
    "LapNumber",
    "LapTime",
    "Stint",
    "Compound",
    "TyreLife",
    "FreshTyre",
    "PitInTime",
    "PitOutTime",
    "TrackStatus",
    "Position",
    "IsAccurate"
]

race_laps = laps[analysis_cols]

In [19]:
race_laps.head()

,Driver,LapNumber,LapTime,Stint,Compound,TyreLife,FreshTyre,PitInTime,PitOutTime,TrackStatus,Position,IsAccurate
0,NOR,1.0,0 days 00:01:31.580000,1.0,MEDIUM,1.0,True,NaT,NaT,1,7.0,False
1,NOR,2.0,0 days 00:01:26.915000,1.0,MEDIUM,2.0,True,NaT,NaT,1,6.0,True
2,NOR,3.0,0 days 00:02:15.827000,1.0,MEDIUM,3.0,True,0 days 01:02:05.923000,NaT,1245,6.0,False
3,NOR,4.0,NaT,2.0,HARD,1.0,True,NaT,0 days 01:32:46.490000,1,6.0,False
4,NOR,5.0,NaT,2.0,HARD,2.0,True,NaT,NaT,1,6.0,False

In [ ]:
race_laps.shape

(1054, 12)

In [21]:
norris_laps = laps.pick_drivers("NOR")

In [22]:
type(norris_laps)

fastf1.core.Laps

In [24]:
norris_laps.shape

(53, 31)

In [26]:
norris_view = norris_laps[analysis_cols]
norris_view.head(10)

,Driver,LapNumber,LapTime,Stint,Compound,TyreLife,FreshTyre,PitInTime,PitOutTime,TrackStatus,Position,IsAccurate
0,NOR,1.0,0 days 00:01:31.580000,1.0,MEDIUM,1.0,True,NaT,NaT,1,7.0,False
1,NOR,2.0,0 days 00:01:26.915000,1.0,MEDIUM,2.0,True,NaT,NaT,1,6.0,True
2,NOR,3.0,0 days 00:02:15.827000,1.0,MEDIUM,3.0,True,0 days 01:02:05.923000,NaT,1245,6.0,False
3,NOR,4.0,NaT,2.0,HARD,1.0,True,NaT,0 days 01:32:46.490000,1,6.0,False
4,NOR,5.0,NaT,2.0,HARD,2.0,True,NaT,NaT,1,6.0,False
5,NOR,6.0,NaT,2.0,HARD,3.0,True,NaT,NaT,12,6.0,False
6,NOR,7.0,0 days 00:01:26.993000,2.0,HARD,4.0,True,NaT,NaT,1,7.0,True
7,NOR,8.0,0 days 00:01:26.433000,2.0,HARD,5.0,True,NaT,NaT,1,7.0,True
8,NOR,9.0,0 days 00:01:26.203000,2.0,HARD,6.0,True,NaT,NaT,1,7.0,True
9,NOR,10.0,0 days 00:01:26.591000,2.0,HARD,7.0,True,NaT,NaT,1,7.0,True